server:
  error:
    path: /error

spring:
  thymeleaf:
    prefix: classpath:/templates/

  datasource:
    url: jdbc:mysql://localhost:3306/slot
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver